apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
  - ../../base
labels:
  - pairs:
      env: dev
images:
  - name: inventory-service
    newName: ghcr.io/zawthanoo/inventory-service
    newTag: 0.0.1-4-0d391d7
replicas:
  - name: inventory-service
    count: 1
configMapGenerator:
  - name: inventory-service-config
    envs:
      - .env
secretGenerator:
  - name: inventory-service-secret
    envs:
      - .secret.env
generatorOptions:
  disableNameSuffixHash: true
