apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
  - ../../base
labels:
  - pairs:
      env: dev
images:
  - name: inventory-service
    newName: ghcr.io/zawthanoo/inventory-service
    newTag: 0.0.1-8-29a1639
replicas:
  - name: inventory-service
    count: 1
configMapGenerator:
  - name: inventory-service-config
    files:
      - application_config_override.yaml
    envs:
      - .env
secretGenerator:
  - name: inventory-service-secret
    files:
      - application_secret_override.yaml
generatorOptions:
  disableNameSuffixHash: true
