apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
  - ../../base
  - configmap.yaml
labels:
  - pairs:
      env: dev
images:
  - name: pos-app
    newName: ghcr.io/zawthanoo/pos-app
    newTag: 14-b700990
replicas:
  - name: pos-app
    count: 1
