apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - ../../base

commonLabels:
  env: dev

images:
  - name: order-service
    newName: asia-southeast1-docker.pkg.dev/YOUR_GCP_PROJECT/YOUR_REPO/order-service
    newTag: latest

replicas:
  - name: order-service
    count: 1

configMapGenerator:
  - name: order-service-config
    envs:
      - .env

secretGenerator:
  - name: order-service-secret
    envs:
      - .secret.env

generatorOptions:
  disableNameSuffixHash: true
