apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
  - ../../base
labels:
  env: dev
images:
  - name: order-service
    newName: ghcr.io/zawthanoo/order-service
    newTag: 5-b153057
replicas:
  - name: order-service
    count: 1
configMapGenerator:
  - name: order-service-config
    envs:
      - .env
secretGenerator:
  - name: order-service-secret
    envs:
      - .secret.env
generatorOptions:
  disableNameSuffixHash: true
