apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: uat

resources:
  - ../../base

labels:
  - pairs:
      env: uat

images:
  - name: order-service
    newName: ghcr.io/zawthanoo/order-service
    newTag: 2-83fb83f

replicas:
  - name: order-service
    count: 2

configMapGenerator:
  - name: order-service-config
    envs:
      - .env

secretGenerator:
  - name: order-service-secret
    envs:
      - .secret.env

generatorOptions:
  disableNameSuffixHash: true
