apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: workshop

resources:
  - ../inventory-service/overlays/dev
  - ../order-service/overlays/dev
  - ../pos-app/overlays/dev
  - ingress.yaml
