spring:
  datasource:
    url: "jdbc:sqlite:file::memory:?cache=shared"
    driver-class-name: org.sqlite.JDBC
    hikari:
      maximum-pool-size: 1
      connection-test-query: SELECT 1
  sql:
    init:
      mode: always
