apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: uat

resources:
  - ../../base

labels:
  env: uat

images:
  - name: inventory-service
    newName: ghcr.io/zawthanoo/inventory-service:
    newTag: 0.0.1-snapshot-1-b996ca3

replicas:
  - name: inventory-service
    count: 2

configMapGenerator:
  - name: inventory-service-config
    envs:
      - .env

secretGenerator:
  - name: inventory-service-secret
    envs:
      - .secret.env

generatorOptions:
  disableNameSuffixHash: true
