apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: uat

resources:
  - ../../base
  - configmap.yaml

labels:
  env: uat

images:
  - name: pos-app
    newName: ghcr.io/zawthanoo/pos-app
    newTag: 8-5afbb15

replicas:
  - name: pos-app
    count: 2
