apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
  labels:
    #    pipelinesascode.tekton.dev/on-event: pull_request
    #    pipelinesascode.tekton.dev/on-target-branch: devteam
    #    repo_name: inventory-service
    app: inventory-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      containers:
        - name: inventory-service
          image: inventory-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3002
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /inventory/products
              port: 3002
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 15
          livenessProbe:
            httpGet:
              path: /inventory/products
              port: 3002
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 15
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          envFrom:
            - configMapRef:
                name: inventory-service-config
          resources:
            requests:
              memory: 1024Mi
          volumeMounts:
            - name: inventory-service-config-volume
              readOnly: true
              mountPath: "/opt/app/config/application_config_override.yaml"
              subPath: application_config_override.yaml
            - name: inventory-service-secret-volume
              readOnly: true
              mountPath: "/opt/app/config/application_secret_override.yaml"
              subPath: application_secret_override.yaml
      imagePullSecrets:
        - name: ghcr-io-registry
      volumes:
        - name: inventory-service-secret-volume
          secret:
            secretName: inventory-service-secret
        - name: inventory-service-config-volume
          configMap:
            name: inventory-service-config
            items:
              - key: application_config_override.yaml
                path: application_config_override.yaml
